//! User-assigned logical identity of a device: nickname, category, purpose,
//! CAT verification and notes.

use serde::{Deserialize, Serialize};

macro_rules! labelled_enum {
    (
        $(#[$meta:meta])*
        pub enum $name:ident { $( $(#[$vmeta:meta])* $variant:ident => ($key:literal, $label:literal) ),+ $(,)? }
    ) => {
        $(#[$meta])*
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(rename_all = "snake_case")]
        pub enum $name { $( $(#[$vmeta])* $variant ),+ }

        impl $name {
            pub const ALL: &'static [$name] = &[$($name::$variant),+];

            /// Stable machine-readable key (database, export files, IPC).
            pub fn as_str(self) -> &'static str {
                match self { $($name::$variant => $key),+ }
            }

            /// Human readable label.
            pub fn label(self) -> &'static str {
                match self { $($name::$variant => $label),+ }
            }

            pub fn parse(value: &str) -> Option<Self> {
                let value = value.trim();
                Self::ALL.iter().copied().find(|v| {
                    v.as_str().eq_ignore_ascii_case(value) || v.label().eq_ignore_ascii_case(value)
                })
            }
        }
    };
}

labelled_enum! {
    /// What the port is used for. Deliberately small and radio-specific.
    pub enum Purpose {
        Cat => ("cat", "CAT"),
        SecondaryCat => ("secondary_cat", "Secondary CAT"),
        Ptt => ("ptt", "PTT"),
        Cw => ("cw", "CW"),
        Programming => ("programming", "Programming"),
        Data => ("data", "Data"),
        Kiss => ("kiss", "KISS"),
        Gps => ("gps", "GPS"),
        Unknown => ("unknown", "Unknown"),
    }
}

labelled_enum! {
    /// Broad device category.
    pub enum Category {
        RadioCat => ("radio_cat", "Radio CAT"),
        Ptt => ("ptt", "PTT"),
        CwKeying => ("cw_keying", "CW Keying"),
        Tnc => ("tnc", "TNC"),
        Kiss => ("kiss", "KISS"),
        Gps => ("gps", "GPS"),
        Rotator => ("rotator", "Rotator"),
        Amplifier => ("amplifier", "Amplifier"),
        AntennaTuner => ("antenna_tuner", "Antenna tuner"),
        ProgrammingCable => ("programming_cable", "Programming cable"),
        BluetoothSerial => ("bluetooth_serial", "Bluetooth serial"),
        VirtualSerial => ("virtual_serial", "Virtual serial"),
        GenericSerial => ("generic_serial", "Generic serial"),
        Other => ("other", "Other"),
    }
}

labelled_enum! {
    /// Whether the user has confirmed that the port accepts CAT commands.
    /// Never set automatically.
    pub enum CatStatus {
        Verified => ("verified", "Verified CAT"),
        NotCat => ("not_cat", "Not CAT"),
        Unknown => ("unknown", "Unknown"),
    }
}

// The enum is generated by a macro shared with enums that have no default,
// so the impl is written by hand.
#[allow(clippy::derivable_impls)]
impl Default for CatStatus {
    fn default() -> Self {
        CatStatus::Unknown
    }
}

/// All user-editable fields of a device.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserIdentity {
    pub nickname: Option<String>,
    pub equipment: Option<String>,
    pub category: Option<Category>,
    pub purpose: Option<Purpose>,
    #[serde(default)]
    pub cat_status: CatStatus,
    pub notes: Option<String>,
}

impl UserIdentity {
    /// `true` when the user has not assigned anything.
    pub fn is_empty(&self) -> bool {
        self.nickname.is_none()
            && self.equipment.is_none()
            && self.category.is_none()
            && self.purpose.is_none()
            && self.cat_status == CatStatus::Unknown
            && self.notes.is_none()
    }

    /// Fills fields that are empty here from `other` (used by merge/import).
    pub fn fill_from(&mut self, other: &UserIdentity) {
        if self.nickname.is_none() {
            self.nickname.clone_from(&other.nickname);
        }
        if self.equipment.is_none() {
            self.equipment.clone_from(&other.equipment);
        }
        if self.category.is_none() {
            self.category = other.category;
        }
        if self.purpose.is_none() {
            self.purpose = other.purpose;
        }
        if self.cat_status == CatStatus::Unknown {
            self.cat_status = other.cat_status;
        }
        match (&mut self.notes, &other.notes) {
            (None, Some(n)) => self.notes = Some(n.clone()),
            (Some(mine), Some(theirs)) if mine.trim() != theirs.trim() => {
                // Keep both notes rather than silently dropping one.
                if !mine.contains(theirs.trim()) {
                    mine.push_str("\n\n");
                    mine.push_str(theirs.trim());
                }
            }
            _ => {}
        }
    }
}

/// A partial update of [`UserIdentity`] sent by the UI. `None` means "leave
/// unchanged"; `Some(None)` means "clear".
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IdentityPatch {
    #[serde(default, with = "double_option")]
    pub nickname: Option<Option<String>>,
    #[serde(default, with = "double_option")]
    pub equipment: Option<Option<String>>,
    #[serde(default, with = "double_option")]
    pub category: Option<Option<Category>>,
    #[serde(default, with = "double_option")]
    pub purpose: Option<Option<Purpose>>,
    #[serde(default)]
    pub cat_status: Option<CatStatus>,
    #[serde(default, with = "double_option")]
    pub notes: Option<Option<String>>,
}

impl IdentityPatch {
    pub fn apply(&self, identity: &mut UserIdentity) {
        if let Some(v) = &self.nickname {
            identity.nickname = clean_text(v.as_deref(), 120);
        }
        if let Some(v) = &self.equipment {
            identity.equipment = clean_text(v.as_deref(), 120);
        }
        if let Some(v) = self.category {
            identity.category = v;
        }
        if let Some(v) = self.purpose {
            identity.purpose = v;
        }
        if let Some(v) = self.cat_status {
            identity.cat_status = v;
        }
        if let Some(v) = &self.notes {
            identity.notes = clean_multiline(v.as_deref(), 4000);
        }
    }
}

/// Trims a single-line text field, collapses internal whitespace and
/// enforces a length limit. Empty strings become `None`.
pub fn clean_text(value: Option<&str>, max_chars: usize) -> Option<String> {
    let value = value?;
    let collapsed = value.split_whitespace().collect::<Vec<_>>().join(" ");
    let truncated: String = collapsed.chars().take(max_chars).collect();
    (!truncated.is_empty()).then_some(truncated)
}

/// Like [`clean_text`] but keeps line breaks.
pub fn clean_multiline(value: Option<&str>, max_chars: usize) -> Option<String> {
    let value = value?.trim();
    let normalized = value.replace("\r\n", "\n");
    let truncated: String = normalized.chars().take(max_chars).collect();
    (!truncated.trim().is_empty()).then_some(truncated)
}

/// Serde helper distinguishing a missing field from an explicit `null`.
mod double_option {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<T: Serialize, S: Serializer>(
        value: &Option<Option<T>>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        match value {
            None => serializer.serialize_none(),
            Some(inner) => inner.serialize(serializer),
        }
    }

    pub fn deserialize<'de, T: Deserialize<'de>, D: Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Option<Option<T>>, D::Error> {
        Option::<T>::deserialize(deserializer).map(Some)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enums_round_trip_keys_and_labels() {
        for p in Purpose::ALL {
            assert_eq!(Purpose::parse(p.as_str()), Some(*p));
            assert_eq!(Purpose::parse(p.label()), Some(*p));
        }
        assert_eq!(
            Category::parse("Antenna tuner"),
            Some(Category::AntennaTuner)
        );
        assert_eq!(CatStatus::parse("verified"), Some(CatStatus::Verified));
        assert_eq!(Purpose::parse("nonsense"), None);
        assert_eq!(
            serde_json::to_string(&Purpose::SecondaryCat).unwrap(),
            "\"secondary_cat\""
        );
    }

    #[test]
    fn patch_distinguishes_missing_from_null() {
        let mut identity = UserIdentity {
            nickname: Some("Old".into()),
            equipment: Some("Yaesu FTDX10".into()),
            ..Default::default()
        };
        let patch: IdentityPatch =
            serde_json::from_str(r#"{"nickname": "  FTDX10   CAT Enhanced ", "equipment": null}"#)
                .unwrap();
        patch.apply(&mut identity);
        assert_eq!(identity.nickname.as_deref(), Some("FTDX10 CAT Enhanced"));
        assert_eq!(identity.equipment, None);

        let patch: IdentityPatch =
            serde_json::from_str(r#"{"purpose": "cat", "catStatus": "verified"}"#).unwrap();
        patch.apply(&mut identity);
        assert_eq!(identity.purpose, Some(Purpose::Cat));
        assert_eq!(identity.cat_status, CatStatus::Verified);
        assert_eq!(identity.nickname.as_deref(), Some("FTDX10 CAT Enhanced"));
    }

    #[test]
    fn blank_text_clears_field() {
        assert_eq!(clean_text(Some("   "), 10), None);
        assert_eq!(
            clean_text(Some("abcdefghijkl"), 5).as_deref(),
            Some("abcde")
        );
        assert_eq!(
            clean_multiline(Some(" line 1\r\nline 2 "), 100).as_deref(),
            Some("line 1\nline 2")
        );
    }

    #[test]
    fn fill_from_keeps_existing_values_and_both_notes() {
        let mut a = UserIdentity {
            nickname: Some("A".into()),
            notes: Some("first".into()),
            ..Default::default()
        };
        let b = UserIdentity {
            nickname: Some("B".into()),
            equipment: Some("IC-7300".into()),
            purpose: Some(Purpose::Cat),
            notes: Some("second".into()),
            ..Default::default()
        };
        a.fill_from(&b);
        assert_eq!(a.nickname.as_deref(), Some("A"));
        assert_eq!(a.equipment.as_deref(), Some("IC-7300"));
        assert_eq!(a.purpose, Some(Purpose::Cat));
        assert_eq!(a.notes.as_deref(), Some("first\n\nsecond"));
    }
}
